//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: friend.proto
// Note: requires additional types generated from: pve.proto
// Note: requires additional types generated from: team.proto
// Note: requires additional types generated from: equip.proto
namespace friend
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendListReq")]
  public partial class FriendListReq : global::ProtoBuf.IExtensible
  {
    public FriendListReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendProtoData")]
  public partial class FriendProtoData : global::ProtoBuf.IExtensible
  {
    public FriendProtoData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _roleName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }

    private int _lv = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }

    private int _playerNo = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playerNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int playerNo
    {
      get { return _playerNo; }
      set { _playerNo = value; }
    }

    private int _combat = (int)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"combat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int combat
    {
      get { return _combat; }
      set { _combat = value; }
    }

    private int _hairCutId = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"hairCutId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int hairCutId
    {
      get { return _hairCutId; }
      set { _hairCutId = value; }
    }

    private int _hairColorId = (int)-1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hairColorId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int hairColorId
    {
      get { return _hairColorId; }
      set { _hairColorId = value; }
    }

    private int _faceId = (int)-1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"faceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int faceId
    {
      get { return _faceId; }
      set { _faceId = value; }
    }

    private bool _isBothAuth = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isBothAuth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBothAuth
    {
      get { return _isBothAuth; }
      set { _isBothAuth = value; }
    }

    private long _lastLoginTime = (long)-1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"lastLoginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long lastLoginTime
    {
      get { return _lastLoginTime; }
      set { _lastLoginTime = value; }
    }

    private bool _isPresent = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"isPresent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isPresent
    {
      get { return _isPresent; }
      set { _isPresent = value; }
    }

    private bool _isPresented = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"isPresented", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isPresented
    {
      get { return _isPresented; }
      set { _isPresented = value; }
    }

    private int _headNo = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"headNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headNo
    {
      get { return _headNo; }
      set { _headNo = value; }
    }

    private int _skinId = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"skinId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skinId
    {
      get { return _skinId; }
      set { _skinId = value; }
    }

    private int _vipLv = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"vipLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vipLv
    {
      get { return _vipLv; }
      set { _vipLv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendListResp")]
  public partial class FriendListResp : global::ProtoBuf.IExtensible
  {
    public FriendListResp() {}
    
    private readonly global::System.Collections.Generic.List<friend.FriendProtoData> _friendList = new global::System.Collections.Generic.List<friend.FriendProtoData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<friend.FriendProtoData> friendList
    {
      get { return _friendList; }
    }
  
    private int _friendListNumUpLimit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"friendListNumUpLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int friendListNumUpLimit
    {
      get { return _friendListNumUpLimit; }
      set { _friendListNumUpLimit = value; }
    }

    private int _getFriendVimTimes = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"getFriendVimTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int getFriendVimTimes
    {
      get { return _getFriendVimTimes; }
      set { _getFriendVimTimes = value; }
    }

    private int _totalGetVimTimes = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"totalGetVimTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalGetVimTimes
    {
      get { return _totalGetVimTimes; }
      set { _totalGetVimTimes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendRecommendListReq")]
  public partial class FriendRecommendListReq : global::ProtoBuf.IExtensible
  {
    public FriendRecommendListReq() {}
    

    private bool _isRefresh = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isRefresh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isRefresh
    {
      get { return _isRefresh; }
      set { _isRefresh = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendRecommendListResp")]
  public partial class FriendRecommendListResp : global::ProtoBuf.IExtensible
  {
    public FriendRecommendListResp() {}
    
    private readonly global::System.Collections.Generic.List<friend.FriendProtoData> _friendList = new global::System.Collections.Generic.List<friend.FriendProtoData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<friend.FriendProtoData> friendList
    {
      get { return _friendList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendAddReq")]
  public partial class FriendAddReq : global::ProtoBuf.IExtensible
  {
    public FriendAddReq() {}
    
    private string _roleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendAddResp")]
  public partial class FriendAddResp : global::ProtoBuf.IExtensible
  {
    public FriendAddResp() {}
    

    private friend.FriendProtoData _newFriend = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"newFriend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public friend.FriendProtoData newFriend
    {
      get { return _newFriend; }
      set { _newFriend = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendAddAnswerReq")]
  public partial class FriendAddAnswerReq : global::ProtoBuf.IExtensible
  {
    public FriendAddAnswerReq() {}
    

    private bool _isClick = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isClick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isClick
    {
      get { return _isClick; }
      set { _isClick = value; }
    }

    private bool _isAgree = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isAgree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isAgree
    {
      get { return _isAgree; }
      set { _isAgree = value; }
    }

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendAddAnswerResp")]
  public partial class FriendAddAnswerResp : global::ProtoBuf.IExtensible
  {
    public FriendAddAnswerResp() {}
    

    private bool _isClick = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isClick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isClick
    {
      get { return _isClick; }
      set { _isClick = value; }
    }

    private bool _isAgree = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isAgree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isAgree
    {
      get { return _isAgree; }
      set { _isAgree = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _newFriendId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"newFriendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> newFriendId
    {
      get { return _newFriendId; }
    }
  
    private readonly global::System.Collections.Generic.List<friend.FriendProtoData> _newFriendList = new global::System.Collections.Generic.List<friend.FriendProtoData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"newFriendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<friend.FriendProtoData> newFriendList
    {
      get { return _newFriendList; }
    }
  

    private int _rejectId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rejectId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rejectId
    {
      get { return _rejectId; }
      set { _rejectId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendDelReq")]
  public partial class FriendDelReq : global::ProtoBuf.IExtensible
  {
    public FriendDelReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendDelResp")]
  public partial class FriendDelResp : global::ProtoBuf.IExtensible
  {
    public FriendDelResp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendPresentVimReq")]
  public partial class FriendPresentVimReq : global::ProtoBuf.IExtensible
  {
    public FriendPresentVimReq() {}
    

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendPresentVimResp")]
  public partial class FriendPresentVimResp : global::ProtoBuf.IExtensible
  {
    public FriendPresentVimResp() {}
    
    private readonly global::System.Collections.Generic.List<int> _id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> id
    {
      get { return _id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendGetVimReq")]
  public partial class FriendGetVimReq : global::ProtoBuf.IExtensible
  {
    public FriendGetVimReq() {}
    

    private bool _isClick = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isClick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isClick
    {
      get { return _isClick; }
      set { _isClick = value; }
    }
    private int _subFuncId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subFuncId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int subFuncId
    {
      get { return _subFuncId; }
      set { _subFuncId = value; }
    }

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendGetVimResp")]
  public partial class FriendGetVimResp : global::ProtoBuf.IExtensible
  {
    public FriendGetVimResp() {}
    

    private bool _isClick = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isClick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isClick
    {
      get { return _isClick; }
      set { _isClick = value; }
    }
    private int _subFuncId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subFuncId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int subFuncId
    {
      get { return _subFuncId; }
      set { _subFuncId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _friendIdList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"friendIdList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> friendIdList
    {
      get { return _friendIdList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendGiftBagReq")]
  public partial class FriendGiftBagReq : global::ProtoBuf.IExtensible
  {
    public FriendGiftBagReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendGiftBagResp")]
  public partial class FriendGiftBagResp : global::ProtoBuf.IExtensible
  {
    public FriendGiftBagResp() {}
    

    private int _remainTimes = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"remainTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int remainTimes
    {
      get { return _remainTimes; }
      set { _remainTimes = value; }
    }
    private readonly global::System.Collections.Generic.List<pve.DropItem> _dropItems = new global::System.Collections.Generic.List<pve.DropItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"dropItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pve.DropItem> dropItems
    {
      get { return _dropItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendLookUpTeamReq")]
  public partial class FriendLookUpTeamReq : global::ProtoBuf.IExtensible
  {
    public FriendLookUpTeamReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _subFuncId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subFuncId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int subFuncId
    {
      get { return _subFuncId; }
      set { _subFuncId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendLookUpTeamResp")]
  public partial class FriendLookUpTeamResp : global::ProtoBuf.IExtensible
  {
    public FriendLookUpTeamResp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private team.TeamDetailProtoData _team;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public team.TeamDetailProtoData team
    {
      get { return _team; }
      set { _team = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendMsgListReq")]
  public partial class FriendMsgListReq : global::ProtoBuf.IExtensible
  {
    public FriendMsgListReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendMsgListResp")]
  public partial class FriendMsgListResp : global::ProtoBuf.IExtensible
  {
    public FriendMsgListResp() {}
    
    private readonly global::System.Collections.Generic.List<friend.FriendProtoData> _friendMsgList = new global::System.Collections.Generic.List<friend.FriendProtoData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friendMsgList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<friend.FriendProtoData> friendMsgList
    {
      get { return _friendMsgList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendFightResp")]
  public partial class FriendFightResp : global::ProtoBuf.IExtensible
  {
    public FriendFightResp() {}
    
    private team.TeamFightProtoData _selfTeamData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"selfTeamData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public team.TeamFightProtoData selfTeamData
    {
      get { return _selfTeamData; }
      set { _selfTeamData = value; }
    }
    private team.TeamFightProtoData _opponentTeamData;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"opponentTeamData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public team.TeamFightProtoData opponentTeamData
    {
      get { return _opponentTeamData; }
      set { _opponentTeamData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RolePlayerProtoData")]
  public partial class RolePlayerProtoData : global::ProtoBuf.IExtensible
  {
    public RolePlayerProtoData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private int _posIndex = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posIndex
    {
      get { return _posIndex; }
      set { _posIndex = value; }
    }

    private int _playerNo = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerNo
    {
      get { return _playerNo; }
      set { _playerNo = value; }
    }

    private int _lv = (int)1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }

    private int _star = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }

    private int _aggrLv = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"aggrLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int aggrLv
    {
      get { return _aggrLv; }
      set { _aggrLv = value; }
    }

    private int _breakLayer = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"breakLayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int breakLayer
    {
      get { return _breakLayer; }
      set { _breakLayer = value; }
    }
    private readonly global::System.Collections.Generic.List<equip.Equip> _equips = new global::System.Collections.Generic.List<equip.Equip>();
    [global::ProtoBuf.ProtoMember(8, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<equip.Equip> equips
    {
      get { return _equips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleHeroProtoData")]
  public partial class RoleHeroProtoData : global::ProtoBuf.IExtensible
  {
    public RoleHeroProtoData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private int _posIndex = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posIndex
    {
      get { return _posIndex; }
      set { _posIndex = value; }
    }

    private int _heroNo = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"heroNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int heroNo
    {
      get { return _heroNo; }
      set { _heroNo = value; }
    }

    private int _lv = (int)1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }

    private int _star = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }

    private int _aggrLv = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"aggrLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int aggrLv
    {
      get { return _aggrLv; }
      set { _aggrLv = value; }
    }

    private int _breakLayer = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"breakLayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int breakLayer
    {
      get { return _breakLayer; }
      set { _breakLayer = value; }
    }
    private readonly global::System.Collections.Generic.List<equip.Equip> _equips = new global::System.Collections.Generic.List<equip.Equip>();
    [global::ProtoBuf.ProtoMember(8, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<equip.Equip> equips
    {
      get { return _equips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleDetInfoProto")]
  public partial class RoleDetInfoProto : global::ProtoBuf.IExtensible
  {
    public RoleDetInfoProto() {}
    
    private team.LineupProtoData _lineup;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lineup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public team.LineupProtoData lineup
    {
      get { return _lineup; }
      set { _lineup = value; }
    }
    private friend.RolePlayerProtoData _player;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public friend.RolePlayerProtoData player
    {
      get { return _player; }
      set { _player = value; }
    }
    private readonly global::System.Collections.Generic.List<friend.RoleHeroProtoData> _heros = new global::System.Collections.Generic.List<friend.RoleHeroProtoData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"heros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<friend.RoleHeroProtoData> heros
    {
      get { return _heros; }
    }
  

    private int _skinId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"skinId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skinId
    {
      get { return _skinId; }
      set { _skinId = value; }
    }

    private int _hairCutId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hairCutId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hairCutId
    {
      get { return _hairCutId; }
      set { _hairCutId = value; }
    }

    private int _hairColorId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"hairColorId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hairColorId
    {
      get { return _hairColorId; }
      set { _hairColorId = value; }
    }

    private int _faceId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"faceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int faceId
    {
      get { return _faceId; }
      set { _faceId = value; }
    }

    private int _headNo = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"headNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headNo
    {
      get { return _headNo; }
      set { _headNo = value; }
    }

    private int _lv = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleInfoLookUpResp")]
  public partial class RoleInfoLookUpResp : global::ProtoBuf.IExtensible
  {
    public RoleInfoLookUpResp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private friend.RoleDetInfoProto _info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public friend.RoleDetInfoProto info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}