//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: task.proto
namespace task
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTasksReq")]
  public partial class GetTasksReq : global::ProtoBuf.IExtensible
  {
    public GetTasksReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskConditionProtoData")]
  public partial class TaskConditionProtoData : global::ProtoBuf.IExtensible
  {
    public TaskConditionProtoData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskProtoData")]
  public partial class TaskProtoData : global::ProtoBuf.IExtensible
  {
    public TaskProtoData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private bool _completed = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"completed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool completed
    {
      get { return _completed; }
      set { _completed = value; }
    }

    private bool _getReward = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"getReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool getReward
    {
      get { return _getReward; }
      set { _getReward = value; }
    }
    private readonly global::System.Collections.Generic.List<task.TaskConditionProtoData> _conditions = new global::System.Collections.Generic.List<task.TaskConditionProtoData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"conditions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<task.TaskConditionProtoData> conditions
    {
      get { return _conditions; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTasksResp")]
  public partial class GetTasksResp : global::ProtoBuf.IExtensible
  {
    public GetTasksResp() {}
    
    private readonly global::System.Collections.Generic.List<task.TaskProtoData> _tasks = new global::System.Collections.Generic.List<task.TaskProtoData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<task.TaskProtoData> tasks
    {
      get { return _tasks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskUpdateResp")]
  public partial class TaskUpdateResp : global::ProtoBuf.IExtensible
  {
    public TaskUpdateResp() {}
    
    private readonly global::System.Collections.Generic.List<task.TaskProtoData> _addTasks = new global::System.Collections.Generic.List<task.TaskProtoData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"addTasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<task.TaskProtoData> addTasks
    {
      get { return _addTasks; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _delTasks = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"delTasks", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> delTasks
    {
      get { return _delTasks; }
    }
  
    private readonly global::System.Collections.Generic.List<task.TaskProtoData> _updateTasks = new global::System.Collections.Generic.List<task.TaskProtoData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"updateTasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<task.TaskProtoData> updateTasks
    {
      get { return _updateTasks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTaskRewardReq")]
  public partial class GetTaskRewardReq : global::ProtoBuf.IExtensible
  {
    public GetTaskRewardReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTaskRewardResp")]
  public partial class GetTaskRewardResp : global::ProtoBuf.IExtensible
  {
    public GetTaskRewardResp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}