//this source code was auto-generated by tolua#, do not modify it
using System;
using System.Collections.Generic;
using LuaInterface;

public static class DelegateFactory
{
	public delegate Delegate DelegateValue(LuaFunction func);
	public static Dictionary<Type, DelegateValue> dict = new Dictionary<Type, DelegateValue>();

	static DelegateFactory()
	{
		Register();
	}

	[NoToLuaAttribute]
	public static void Register()
	{
		dict.Clear();
		dict.Add(typeof(System.Action), System_Action);
		dict.Add(typeof(System.Action<UnityEngine.GameObject>), System_Action_UnityEngine_GameObject);
		dict.Add(typeof(System.Action<int>), System_Action_int);
		dict.Add(typeof(System.Action<float>), System_Action_float);
		dict.Add(typeof(System.Action<UnityEngine.Vector3>), System_Action_UnityEngine_Vector3);
		dict.Add(typeof(System.Action<Logic.Character.PlayerEntity>), System_Action_Logic_Character_PlayerEntity);
		dict.Add(typeof(System.Action<Logic.Character.PetEntity>), System_Action_Logic_Character_PetEntity);
		dict.Add(typeof(System.Action<Logic.Character.HeroEntity>), System_Action_Logic_Character_HeroEntity);
		dict.Add(typeof(UnityEngine.Events.UnityAction), UnityEngine_Events_UnityAction);
		dict.Add(typeof(UnityEngine.Events.UnityAction<int>), UnityEngine_Events_UnityAction_int);
		dict.Add(typeof(UnityEngine.Events.UnityAction<string>), UnityEngine_Events_UnityAction_string);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.Vector2>), UnityEngine_Events_UnityAction_UnityEngine_Vector2);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.GameObject,int>), UnityEngine_Events_UnityAction_UnityEngine_GameObject_int);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.GameObject>), UnityEngine_Events_UnityAction_UnityEngine_GameObject);
		dict.Add(typeof(UnityEngine.Canvas.WillRenderCanvases), UnityEngine_Canvas_WillRenderCanvases);
		dict.Add(typeof(UnityEngine.RectTransform.ReapplyDrivenProperties), UnityEngine_RectTransform_ReapplyDrivenProperties);
		dict.Add(typeof(UnityEngine.Camera.CameraCallback), UnityEngine_Camera_CameraCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMReaderCallback), UnityEngine_AudioClip_PCMReaderCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMSetPositionCallback), UnityEngine_AudioClip_PCMSetPositionCallback);
		dict.Add(typeof(UnityEngine.Application.LogCallback), UnityEngine_Application_LogCallback);
		dict.Add(typeof(UnityEngine.UI.InputField.OnValidateInput), UnityEngine_UI_InputField_OnValidateInput);
		dict.Add(typeof(UnityEngine.Events.UnityAction<bool>), UnityEngine_Events_UnityAction_bool);
		dict.Add(typeof(System.Action<object>), System_Action_object);
		dict.Add(typeof(System.Action<UnityEngine.Color>), System_Action_UnityEngine_Color);
		dict.Add(typeof(System.Action<UnityEngine.Vector2>), System_Action_UnityEngine_Vector2);
		dict.Add(typeof(System.Action<float,object>), System_Action_float_object);
		dict.Add(typeof(System.Action<LTEvent>), System_Action_LTEvent);
		dict.Add(typeof(System.Action<float,float>), System_Action_float_float);
		dict.Add(typeof(System.Action<UnityEngine.Vector3,object>), System_Action_UnityEngine_Vector3_object);
		dict.Add(typeof(System.Func<Observers.Interfaces.INotification,bool>), System_Func_Observers_Interfaces_INotification_bool);
		dict.Add(typeof(System.Action<string>), System_Action_string);
		dict.Add(typeof(System.Action<string,float>), System_Action_string_float);
		dict.Add(typeof(System.Action<string,Common.ResMgr.ResLoaderObj>), System_Action_string_Common_ResMgr_ResLoaderObj);
		dict.Add(typeof(System.Action<UnityEngine.Object>), System_Action_UnityEngine_Object);
		dict.Add(typeof(System.Action<UnityEngine.Sprite>), System_Action_UnityEngine_Sprite);
		dict.Add(typeof(Logic.UI.UIMgr.OnUIViewOpenDelegate), Logic_UI_UIMgr_OnUIViewOpenDelegate);
		dict.Add(typeof(System.Action<PathologicalGames.SpawnPool>), System_Action_PathologicalGames_SpawnPool);
		dict.Add(typeof(System.Action<Logic.Character.EnemyPlayerEntity>), System_Action_Logic_Character_EnemyPlayerEntity);
		dict.Add(typeof(System.Action<Logic.Character.EnemyEntity>), System_Action_Logic_Character_EnemyEntity);
		dict.Add(typeof(System.Action<bool>), System_Action_bool);
		dict.Add(typeof(System.Predicate<Logic.Skill.Model.SkillDesInfo>), System_Predicate_Logic_Skill_Model_SkillDesInfo);
		dict.Add(typeof(System.Action<Logic.Skill.Model.SkillDesInfo>), System_Action_Logic_Skill_Model_SkillDesInfo);
		dict.Add(typeof(System.Comparison<Logic.Skill.Model.SkillDesInfo>), System_Comparison_Logic_Skill_Model_SkillDesInfo);
		dict.Add(typeof(System.Predicate<System.Collections.Generic.KeyValuePair<int,float>>), System_Predicate_System_Collections_Generic_KeyValuePair_int_float);
		dict.Add(typeof(System.Action<System.Collections.Generic.KeyValuePair<int,float>>), System_Action_System_Collections_Generic_KeyValuePair_int_float);
		dict.Add(typeof(System.Comparison<System.Collections.Generic.KeyValuePair<int,float>>), System_Comparison_System_Collections_Generic_KeyValuePair_int_float);
		dict.Add(typeof(System.Predicate<UnityEngine.UI.Dropdown.OptionData>), System_Predicate_UnityEngine_UI_Dropdown_OptionData);
		dict.Add(typeof(System.Action<UnityEngine.UI.Dropdown.OptionData>), System_Action_UnityEngine_UI_Dropdown_OptionData);
		dict.Add(typeof(System.Comparison<UnityEngine.UI.Dropdown.OptionData>), System_Comparison_UnityEngine_UI_Dropdown_OptionData);
		dict.Add(typeof(System.Predicate<Logic.Game.Model.GameResData>), System_Predicate_Logic_Game_Model_GameResData);
		dict.Add(typeof(System.Action<Logic.Game.Model.GameResData>), System_Action_Logic_Game_Model_GameResData);
		dict.Add(typeof(System.Comparison<Logic.Game.Model.GameResData>), System_Comparison_Logic_Game_Model_GameResData);
	}

    [NoToLuaAttribute]
    public static Delegate CreateDelegate(Type t, LuaFunction func = null)
    {
        DelegateValue create = null;

        if (!dict.TryGetValue(t, out create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));            
        }
        
        return create(func);        
    }

    [NoToLuaAttribute]
    public static Delegate RemoveDelegate(Delegate obj, LuaFunction func)
    {
        LuaState state = func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld.func == func)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                break;
            }
        }

        return obj;
    }

	class System_Action_Event : LuaDelegate
	{
		public System_Action_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate System_Action(LuaFunction func)
	{
		if (func == null)
		{
			System.Action fn = delegate { };
			return fn;
		}

		System.Action d = (new System_Action_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_GameObject_Event : LuaDelegate
	{
		public System_Action_UnityEngine_GameObject_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_GameObject(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.GameObject> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.GameObject> d = (new System_Action_UnityEngine_GameObject_Event(func)).Call;
		return d;
	}

	class System_Action_int_Event : LuaDelegate
	{
		public System_Action_int_Event(LuaFunction func) : base(func) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_int(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<int> fn = delegate { };
			return fn;
		}

		System.Action<int> d = (new System_Action_int_Event(func)).Call;
		return d;
	}

	class System_Action_float_Event : LuaDelegate
	{
		public System_Action_float_Event(LuaFunction func) : base(func) { }

		public void Call(float param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_float(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<float> fn = delegate { };
			return fn;
		}

		System.Action<float> d = (new System_Action_float_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_Vector3_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Vector3_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Vector3 param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Vector3(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Vector3> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.Vector3> d = (new System_Action_UnityEngine_Vector3_Event(func)).Call;
		return d;
	}

	class System_Action_Logic_Character_PlayerEntity_Event : LuaDelegate
	{
		public System_Action_Logic_Character_PlayerEntity_Event(LuaFunction func) : base(func) { }

		public void Call(Logic.Character.PlayerEntity param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_Logic_Character_PlayerEntity(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<Logic.Character.PlayerEntity> fn = delegate { };
			return fn;
		}

		System.Action<Logic.Character.PlayerEntity> d = (new System_Action_Logic_Character_PlayerEntity_Event(func)).Call;
		return d;
	}

	class System_Action_Logic_Character_PetEntity_Event : LuaDelegate
	{
		public System_Action_Logic_Character_PetEntity_Event(LuaFunction func) : base(func) { }

		public void Call(Logic.Character.PetEntity param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_Logic_Character_PetEntity(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<Logic.Character.PetEntity> fn = delegate { };
			return fn;
		}

		System.Action<Logic.Character.PetEntity> d = (new System_Action_Logic_Character_PetEntity_Event(func)).Call;
		return d;
	}

	class System_Action_Logic_Character_HeroEntity_Event : LuaDelegate
	{
		public System_Action_Logic_Character_HeroEntity_Event(LuaFunction func) : base(func) { }

		public void Call(Logic.Character.HeroEntity param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_Logic_Character_HeroEntity(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<Logic.Character.HeroEntity> fn = delegate { };
			return fn;
		}

		System.Action<Logic.Character.HeroEntity> d = (new System_Action_Logic_Character_HeroEntity_Event(func)).Call;
		return d;
	}

	class UnityEngine_Events_UnityAction_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction fn = delegate { };
			return fn;
		}

		UnityEngine.Events.UnityAction d = (new UnityEngine_Events_UnityAction_Event(func)).Call;
		return d;
	}

	class UnityEngine_Events_UnityAction_int_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_int_Event(LuaFunction func) : base(func) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_int(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<int> fn = delegate { };
			return fn;
		}

		UnityEngine.Events.UnityAction<int> d = (new UnityEngine_Events_UnityAction_int_Event(func)).Call;
		return d;
	}

	class UnityEngine_Events_UnityAction_string_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_string_Event(LuaFunction func) : base(func) { }

		public void Call(string param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_string(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<string> fn = delegate { };
			return fn;
		}

		UnityEngine.Events.UnityAction<string> d = (new UnityEngine_Events_UnityAction_string_Event(func)).Call;
		return d;
	}

	class UnityEngine_Events_UnityAction_UnityEngine_Vector2_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_Vector2_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Vector2 param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_UnityEngine_Vector2(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.Vector2> fn = delegate { };
			return fn;
		}

		UnityEngine.Events.UnityAction<UnityEngine.Vector2> d = (new UnityEngine_Events_UnityAction_UnityEngine_Vector2_Event(func)).Call;
		return d;
	}

	class UnityEngine_Events_UnityAction_UnityEngine_GameObject_int_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_GameObject_int_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0,int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_UnityEngine_GameObject_int(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.GameObject,int> fn = delegate { };
			return fn;
		}

		UnityEngine.Events.UnityAction<UnityEngine.GameObject,int> d = (new UnityEngine_Events_UnityAction_UnityEngine_GameObject_int_Event(func)).Call;
		return d;
	}

	class UnityEngine_Events_UnityAction_UnityEngine_GameObject_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_GameObject_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_UnityEngine_GameObject(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.GameObject> fn = delegate { };
			return fn;
		}

		UnityEngine.Events.UnityAction<UnityEngine.GameObject> d = (new UnityEngine_Events_UnityAction_UnityEngine_GameObject_Event(func)).Call;
		return d;
	}

	class UnityEngine_Canvas_WillRenderCanvases_Event : LuaDelegate
	{
		public UnityEngine_Canvas_WillRenderCanvases_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate UnityEngine_Canvas_WillRenderCanvases(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Canvas.WillRenderCanvases fn = delegate { };
			return fn;
		}

		UnityEngine.Canvas.WillRenderCanvases d = (new UnityEngine_Canvas_WillRenderCanvases_Event(func)).Call;
		return d;
	}

	class UnityEngine_RectTransform_ReapplyDrivenProperties_Event : LuaDelegate
	{
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_RectTransform_ReapplyDrivenProperties(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.RectTransform.ReapplyDrivenProperties fn = delegate { };
			return fn;
		}

		UnityEngine.RectTransform.ReapplyDrivenProperties d = (new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func)).Call;
		return d;
	}

	class UnityEngine_Camera_CameraCallback_Event : LuaDelegate
	{
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Camera_CameraCallback(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Camera.CameraCallback fn = delegate { };
			return fn;
		}

		UnityEngine.Camera.CameraCallback d = (new UnityEngine_Camera_CameraCallback_Event(func)).Call;
		return d;
	}

	class UnityEngine_AudioClip_PCMReaderCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func) : base(func) { }

		public void Call(float[] param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMReaderCallback(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMReaderCallback fn = delegate { };
			return fn;
		}

		UnityEngine.AudioClip.PCMReaderCallback d = (new UnityEngine_AudioClip_PCMReaderCallback_Event(func)).Call;
		return d;
	}

	class UnityEngine_AudioClip_PCMSetPositionCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func) : base(func) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMSetPositionCallback(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMSetPositionCallback fn = delegate { };
			return fn;
		}

		UnityEngine.AudioClip.PCMSetPositionCallback d = (new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func)).Call;
		return d;
	}

	class UnityEngine_Application_LogCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_LogCallback_Event(LuaFunction func) : base(func) { }

		public void Call(string param0,string param1,UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_LogCallback(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Application.LogCallback fn = delegate { };
			return fn;
		}

		UnityEngine.Application.LogCallback d = (new UnityEngine_Application_LogCallback_Event(func)).Call;
		return d;
	}

	class UnityEngine_UI_InputField_OnValidateInput_Event : LuaDelegate
	{
		public UnityEngine_UI_InputField_OnValidateInput_Event(LuaFunction func) : base(func) { }

		public char Call(string param0,int param1,char param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			char ret = (char)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate UnityEngine_UI_InputField_OnValidateInput(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.UI.InputField.OnValidateInput fn = delegate { return '\0'; };
			return fn;
		}

		UnityEngine.UI.InputField.OnValidateInput d = (new UnityEngine_UI_InputField_OnValidateInput_Event(func)).Call;
		return d;
	}

	class UnityEngine_Events_UnityAction_bool_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_bool_Event(LuaFunction func) : base(func) { }

		public void Call(bool param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_bool(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<bool> fn = delegate { };
			return fn;
		}

		UnityEngine.Events.UnityAction<bool> d = (new UnityEngine_Events_UnityAction_bool_Event(func)).Call;
		return d;
	}

	class System_Action_object_Event : LuaDelegate
	{
		public System_Action_object_Event(LuaFunction func) : base(func) { }

		public void Call(object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_object(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<object> fn = delegate { };
			return fn;
		}

		System.Action<object> d = (new System_Action_object_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_Color_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Color_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Color param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Color(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Color> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.Color> d = (new System_Action_UnityEngine_Color_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_Vector2_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Vector2_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Vector2 param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Vector2(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Vector2> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.Vector2> d = (new System_Action_UnityEngine_Vector2_Event(func)).Call;
		return d;
	}

	class System_Action_float_object_Event : LuaDelegate
	{
		public System_Action_float_object_Event(LuaFunction func) : base(func) { }

		public void Call(float param0,object param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_float_object(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<float,object> fn = delegate { };
			return fn;
		}

		System.Action<float,object> d = (new System_Action_float_object_Event(func)).Call;
		return d;
	}

	class System_Action_LTEvent_Event : LuaDelegate
	{
		public System_Action_LTEvent_Event(LuaFunction func) : base(func) { }

		public void Call(LTEvent param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_LTEvent(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<LTEvent> fn = delegate { };
			return fn;
		}

		System.Action<LTEvent> d = (new System_Action_LTEvent_Event(func)).Call;
		return d;
	}

	class System_Action_float_float_Event : LuaDelegate
	{
		public System_Action_float_float_Event(LuaFunction func) : base(func) { }

		public void Call(float param0,float param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_float_float(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<float,float> fn = delegate { };
			return fn;
		}

		System.Action<float,float> d = (new System_Action_float_float_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_Vector3_object_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Vector3_object_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Vector3 param0,object param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Vector3_object(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Vector3,object> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.Vector3,object> d = (new System_Action_UnityEngine_Vector3_object_Event(func)).Call;
		return d;
	}

	class System_Func_Observers_Interfaces_INotification_bool_Event : LuaDelegate
	{
		public System_Func_Observers_Interfaces_INotification_bool_Event(LuaFunction func) : base(func) { }

		public bool Call(Observers.Interfaces.INotification param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Func_Observers_Interfaces_INotification_bool(LuaFunction func)
	{
		if (func == null)
		{
			System.Func<Observers.Interfaces.INotification,bool> fn = delegate { return false; };
			return fn;
		}

		System.Func<Observers.Interfaces.INotification,bool> d = (new System_Func_Observers_Interfaces_INotification_bool_Event(func)).Call;
		return d;
	}

	class System_Action_string_Event : LuaDelegate
	{
		public System_Action_string_Event(LuaFunction func) : base(func) { }

		public void Call(string param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_string(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<string> fn = delegate { };
			return fn;
		}

		System.Action<string> d = (new System_Action_string_Event(func)).Call;
		return d;
	}

	class System_Action_string_float_Event : LuaDelegate
	{
		public System_Action_string_float_Event(LuaFunction func) : base(func) { }

		public void Call(string param0,float param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_string_float(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<string,float> fn = delegate { };
			return fn;
		}

		System.Action<string,float> d = (new System_Action_string_float_Event(func)).Call;
		return d;
	}

	class System_Action_string_Common_ResMgr_ResLoaderObj_Event : LuaDelegate
	{
		public System_Action_string_Common_ResMgr_ResLoaderObj_Event(LuaFunction func) : base(func) { }

		public void Call(string param0,Common.ResMgr.ResLoaderObj param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_string_Common_ResMgr_ResLoaderObj(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<string,Common.ResMgr.ResLoaderObj> fn = delegate { };
			return fn;
		}

		System.Action<string,Common.ResMgr.ResLoaderObj> d = (new System_Action_string_Common_ResMgr_ResLoaderObj_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_Object_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Object_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Object(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Object> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.Object> d = (new System_Action_UnityEngine_Object_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_Sprite_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Sprite_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Sprite param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Sprite(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Sprite> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.Sprite> d = (new System_Action_UnityEngine_Sprite_Event(func)).Call;
		return d;
	}

	class Logic_UI_UIMgr_OnUIViewOpenDelegate_Event : LuaDelegate
	{
		public Logic_UI_UIMgr_OnUIViewOpenDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(string param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate Logic_UI_UIMgr_OnUIViewOpenDelegate(LuaFunction func)
	{
		if (func == null)
		{
			Logic.UI.UIMgr.OnUIViewOpenDelegate fn = delegate { };
			return fn;
		}

		Logic.UI.UIMgr.OnUIViewOpenDelegate d = (new Logic_UI_UIMgr_OnUIViewOpenDelegate_Event(func)).Call;
		return d;
	}

	class System_Action_PathologicalGames_SpawnPool_Event : LuaDelegate
	{
		public System_Action_PathologicalGames_SpawnPool_Event(LuaFunction func) : base(func) { }

		public void Call(PathologicalGames.SpawnPool param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_PathologicalGames_SpawnPool(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<PathologicalGames.SpawnPool> fn = delegate { };
			return fn;
		}

		System.Action<PathologicalGames.SpawnPool> d = (new System_Action_PathologicalGames_SpawnPool_Event(func)).Call;
		return d;
	}

	class System_Action_Logic_Character_EnemyPlayerEntity_Event : LuaDelegate
	{
		public System_Action_Logic_Character_EnemyPlayerEntity_Event(LuaFunction func) : base(func) { }

		public void Call(Logic.Character.EnemyPlayerEntity param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_Logic_Character_EnemyPlayerEntity(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<Logic.Character.EnemyPlayerEntity> fn = delegate { };
			return fn;
		}

		System.Action<Logic.Character.EnemyPlayerEntity> d = (new System_Action_Logic_Character_EnemyPlayerEntity_Event(func)).Call;
		return d;
	}

	class System_Action_Logic_Character_EnemyEntity_Event : LuaDelegate
	{
		public System_Action_Logic_Character_EnemyEntity_Event(LuaFunction func) : base(func) { }

		public void Call(Logic.Character.EnemyEntity param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_Logic_Character_EnemyEntity(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<Logic.Character.EnemyEntity> fn = delegate { };
			return fn;
		}

		System.Action<Logic.Character.EnemyEntity> d = (new System_Action_Logic_Character_EnemyEntity_Event(func)).Call;
		return d;
	}

	class System_Action_bool_Event : LuaDelegate
	{
		public System_Action_bool_Event(LuaFunction func) : base(func) { }

		public void Call(bool param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_bool(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<bool> fn = delegate { };
			return fn;
		}

		System.Action<bool> d = (new System_Action_bool_Event(func)).Call;
		return d;
	}

	class System_Predicate_Logic_Skill_Model_SkillDesInfo_Event : LuaDelegate
	{
		public System_Predicate_Logic_Skill_Model_SkillDesInfo_Event(LuaFunction func) : base(func) { }

		public bool Call(Logic.Skill.Model.SkillDesInfo param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Predicate_Logic_Skill_Model_SkillDesInfo(LuaFunction func)
	{
		if (func == null)
		{
			System.Predicate<Logic.Skill.Model.SkillDesInfo> fn = delegate { return false; };
			return fn;
		}

		System.Predicate<Logic.Skill.Model.SkillDesInfo> d = (new System_Predicate_Logic_Skill_Model_SkillDesInfo_Event(func)).Call;
		return d;
	}

	class System_Action_Logic_Skill_Model_SkillDesInfo_Event : LuaDelegate
	{
		public System_Action_Logic_Skill_Model_SkillDesInfo_Event(LuaFunction func) : base(func) { }

		public void Call(Logic.Skill.Model.SkillDesInfo param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_Logic_Skill_Model_SkillDesInfo(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<Logic.Skill.Model.SkillDesInfo> fn = delegate { };
			return fn;
		}

		System.Action<Logic.Skill.Model.SkillDesInfo> d = (new System_Action_Logic_Skill_Model_SkillDesInfo_Event(func)).Call;
		return d;
	}

	class System_Comparison_Logic_Skill_Model_SkillDesInfo_Event : LuaDelegate
	{
		public System_Comparison_Logic_Skill_Model_SkillDesInfo_Event(LuaFunction func) : base(func) { }

		public int Call(Logic.Skill.Model.SkillDesInfo param0,Logic.Skill.Model.SkillDesInfo param1)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Comparison_Logic_Skill_Model_SkillDesInfo(LuaFunction func)
	{
		if (func == null)
		{
			System.Comparison<Logic.Skill.Model.SkillDesInfo> fn = delegate { return 0; };
			return fn;
		}

		System.Comparison<Logic.Skill.Model.SkillDesInfo> d = (new System_Comparison_Logic_Skill_Model_SkillDesInfo_Event(func)).Call;
		return d;
	}

	class System_Predicate_System_Collections_Generic_KeyValuePair_int_float_Event : LuaDelegate
	{
		public System_Predicate_System_Collections_Generic_KeyValuePair_int_float_Event(LuaFunction func) : base(func) { }

		public bool Call(System.Collections.Generic.KeyValuePair<int,float> param0)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Predicate_System_Collections_Generic_KeyValuePair_int_float(LuaFunction func)
	{
		if (func == null)
		{
			System.Predicate<System.Collections.Generic.KeyValuePair<int,float>> fn = delegate { return false; };
			return fn;
		}

		System.Predicate<System.Collections.Generic.KeyValuePair<int,float>> d = (new System_Predicate_System_Collections_Generic_KeyValuePair_int_float_Event(func)).Call;
		return d;
	}

	class System_Action_System_Collections_Generic_KeyValuePair_int_float_Event : LuaDelegate
	{
		public System_Action_System_Collections_Generic_KeyValuePair_int_float_Event(LuaFunction func) : base(func) { }

		public void Call(System.Collections.Generic.KeyValuePair<int,float> param0)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_System_Collections_Generic_KeyValuePair_int_float(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<System.Collections.Generic.KeyValuePair<int,float>> fn = delegate { };
			return fn;
		}

		System.Action<System.Collections.Generic.KeyValuePair<int,float>> d = (new System_Action_System_Collections_Generic_KeyValuePair_int_float_Event(func)).Call;
		return d;
	}

	class System_Comparison_System_Collections_Generic_KeyValuePair_int_float_Event : LuaDelegate
	{
		public System_Comparison_System_Collections_Generic_KeyValuePair_int_float_Event(LuaFunction func) : base(func) { }

		public int Call(System.Collections.Generic.KeyValuePair<int,float> param0,System.Collections.Generic.KeyValuePair<int,float> param1)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.PushValue(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Comparison_System_Collections_Generic_KeyValuePair_int_float(LuaFunction func)
	{
		if (func == null)
		{
			System.Comparison<System.Collections.Generic.KeyValuePair<int,float>> fn = delegate { return 0; };
			return fn;
		}

		System.Comparison<System.Collections.Generic.KeyValuePair<int,float>> d = (new System_Comparison_System_Collections_Generic_KeyValuePair_int_float_Event(func)).Call;
		return d;
	}

	class System_Predicate_UnityEngine_UI_Dropdown_OptionData_Event : LuaDelegate
	{
		public System_Predicate_UnityEngine_UI_Dropdown_OptionData_Event(LuaFunction func) : base(func) { }

		public bool Call(UnityEngine.UI.Dropdown.OptionData param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Predicate_UnityEngine_UI_Dropdown_OptionData(LuaFunction func)
	{
		if (func == null)
		{
			System.Predicate<UnityEngine.UI.Dropdown.OptionData> fn = delegate { return false; };
			return fn;
		}

		System.Predicate<UnityEngine.UI.Dropdown.OptionData> d = (new System_Predicate_UnityEngine_UI_Dropdown_OptionData_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_UI_Dropdown_OptionData_Event : LuaDelegate
	{
		public System_Action_UnityEngine_UI_Dropdown_OptionData_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.UI.Dropdown.OptionData param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_UI_Dropdown_OptionData(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.UI.Dropdown.OptionData> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.UI.Dropdown.OptionData> d = (new System_Action_UnityEngine_UI_Dropdown_OptionData_Event(func)).Call;
		return d;
	}

	class System_Comparison_UnityEngine_UI_Dropdown_OptionData_Event : LuaDelegate
	{
		public System_Comparison_UnityEngine_UI_Dropdown_OptionData_Event(LuaFunction func) : base(func) { }

		public int Call(UnityEngine.UI.Dropdown.OptionData param0,UnityEngine.UI.Dropdown.OptionData param1)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Comparison_UnityEngine_UI_Dropdown_OptionData(LuaFunction func)
	{
		if (func == null)
		{
			System.Comparison<UnityEngine.UI.Dropdown.OptionData> fn = delegate { return 0; };
			return fn;
		}

		System.Comparison<UnityEngine.UI.Dropdown.OptionData> d = (new System_Comparison_UnityEngine_UI_Dropdown_OptionData_Event(func)).Call;
		return d;
	}

	class System_Predicate_Logic_Game_Model_GameResData_Event : LuaDelegate
	{
		public System_Predicate_Logic_Game_Model_GameResData_Event(LuaFunction func) : base(func) { }

		public bool Call(Logic.Game.Model.GameResData param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Predicate_Logic_Game_Model_GameResData(LuaFunction func)
	{
		if (func == null)
		{
			System.Predicate<Logic.Game.Model.GameResData> fn = delegate { return false; };
			return fn;
		}

		System.Predicate<Logic.Game.Model.GameResData> d = (new System_Predicate_Logic_Game_Model_GameResData_Event(func)).Call;
		return d;
	}

	class System_Action_Logic_Game_Model_GameResData_Event : LuaDelegate
	{
		public System_Action_Logic_Game_Model_GameResData_Event(LuaFunction func) : base(func) { }

		public void Call(Logic.Game.Model.GameResData param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_Logic_Game_Model_GameResData(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<Logic.Game.Model.GameResData> fn = delegate { };
			return fn;
		}

		System.Action<Logic.Game.Model.GameResData> d = (new System_Action_Logic_Game_Model_GameResData_Event(func)).Call;
		return d;
	}

	class System_Comparison_Logic_Game_Model_GameResData_Event : LuaDelegate
	{
		public System_Comparison_Logic_Game_Model_GameResData_Event(LuaFunction func) : base(func) { }

		public int Call(Logic.Game.Model.GameResData param0,Logic.Game.Model.GameResData param1)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Comparison_Logic_Game_Model_GameResData(LuaFunction func)
	{
		if (func == null)
		{
			System.Comparison<Logic.Game.Model.GameResData> fn = delegate { return 0; };
			return fn;
		}

		System.Comparison<Logic.Game.Model.GameResData> d = (new System_Comparison_Logic_Game_Model_GameResData_Event(func)).Call;
		return d;
	}

}

