//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Logic_Enums_BaseResTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(Logic.Enums.BaseResType));
		L.RegVar("None", get_None, null);
		L.RegVar("Resource", get_Resource, null);
		L.RegVar("Hero", get_Hero, null);
		L.RegVar("Equipment", get_Equipment, null);
		L.RegVar("Item", get_Item, null);
		L.RegVar("Hero_Exp", get_Hero_Exp, null);
		L.RegVar("Account_Exp", get_Account_Exp, null);
		L.RegVar("Gold", get_Gold, null);
		L.RegVar("Diamond", get_Diamond, null);
		L.RegVar("Crystal", get_Crystal, null);
		L.RegVar("PveAction", get_PveAction, null);
		L.RegVar("TowerAction", get_TowerAction, null);
		L.RegVar("PvpAction", get_PvpAction, null);
		L.RegVar("Honor", get_Honor, null);
		L.RegVar("ArenaPoint", get_ArenaPoint, null);
		L.RegVar("ExpeditionPoint", get_ExpeditionPoint, null);
		L.RegVar("WorldBossResource", get_WorldBossResource, null);
		L.RegVar("FromationTrainPoint", get_FromationTrainPoint, null);
		L.RegVar("RMB", get_RMB, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Resource(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.Resource);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Hero(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.Hero);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Equipment(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.Equipment);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Item(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.Item);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Hero_Exp(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.Hero_Exp);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Account_Exp(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.Account_Exp);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Gold(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.Gold);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Diamond(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.Diamond);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Crystal(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.Crystal);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PveAction(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.PveAction);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TowerAction(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.TowerAction);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PvpAction(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.PvpAction);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Honor(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.Honor);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ArenaPoint(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.ArenaPoint);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExpeditionPoint(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.ExpeditionPoint);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WorldBossResource(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.WorldBossResource);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FromationTrainPoint(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.FromationTrainPoint);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RMB(IntPtr L)
	{
		ToLua.Push(L, Logic.Enums.BaseResType.RMB);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		Logic.Enums.BaseResType o = (Logic.Enums.BaseResType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

