//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: fight.proto
// Note: requires additional types generated from: team.proto
// Note: requires additional types generated from: common.proto
namespace Logic.Protocol.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RealTimeFightProtoData")]
  public partial class RealTimeFightProtoData : global::ProtoBuf.IExtensible
  {
    public RealTimeFightProtoData() {}
    
    private Logic.Protocol.Model.TeamFightProtoData _teamData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"teamData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Logic.Protocol.Model.TeamFightProtoData teamData
    {
      get { return _teamData; }
      set { _teamData = value; }
    }
    private int _roleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private int _gateServerId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gateServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gateServerId
    {
      get { return _gateServerId; }
      set { _gateServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightInit")]
  public partial class FightInit : global::ProtoBuf.IExtensible
  {
    public FightInit() {}
    
    private Logic.Protocol.Model.RealTimeFightProtoData _side1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"side1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Logic.Protocol.Model.RealTimeFightProtoData side1
    {
      get { return _side1; }
      set { _side1 = value; }
    }
    private Logic.Protocol.Model.RealTimeFightProtoData _side2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"side2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Logic.Protocol.Model.RealTimeFightProtoData side2
    {
      get { return _side2; }
      set { _side2 = value; }
    }
    private int _randomSeed;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"randomSeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int randomSeed
    {
      get { return _randomSeed; }
      set { _randomSeed = value; }
    }
    private int _fightId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RealTimeFightDataResp")]
  public partial class RealTimeFightDataResp : global::ProtoBuf.IExtensible
  {
    public RealTimeFightDataResp() {}
    
    private Logic.Protocol.Model.TeamFightProtoData _selfTeamData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"selfTeamData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Logic.Protocol.Model.TeamFightProtoData selfTeamData
    {
      get { return _selfTeamData; }
      set { _selfTeamData = value; }
    }
    private Logic.Protocol.Model.TeamFightProtoData _opponentTeamData;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"opponentTeamData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Logic.Protocol.Model.TeamFightProtoData opponentTeamData
    {
      get { return _opponentTeamData; }
      set { _opponentTeamData = value; }
    }
    private int _randomSeed;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"randomSeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int randomSeed
    {
      get { return _randomSeed; }
      set { _randomSeed = value; }
    }
    private int _fightId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }

    private bool _isHome = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isHome", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isHome
    {
      get { return _isHome; }
      set { _isHome = value; }
    }
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.FightCmdSynResp> _cmdList = new global::System.Collections.Generic.List<Logic.Protocol.Model.FightCmdSynResp>();
    [global::ProtoBuf.ProtoMember(6, Name=@"cmdList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.FightCmdSynResp> cmdList
    {
      get { return _cmdList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Gethit")]
  public partial class Gethit : global::ProtoBuf.IExtensible
  {
    public Gethit() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _hurt;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hurt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hurt
    {
      get { return _hurt; }
      set { _hurt = value; }
    }

    private int _judgeType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"judgeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int judgeType
    {
      get { return _judgeType; }
      set { _judgeType = value; }
    }

    private int _remainHp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"remainHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int remainHp
    {
      get { return _remainHp; }
      set { _remainHp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mechanics")]
  public partial class Mechanics : global::ProtoBuf.IExtensible
  {
    public Mechanics() {}
    
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.Gethit> _gethits = new global::System.Collections.Generic.List<Logic.Protocol.Model.Gethit>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gethits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.Gethit> gethits
    {
      get { return _gethits; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Buff")]
  public partial class Buff : global::ProtoBuf.IExtensible
  {
    public Buff() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _desId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"desId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int desId
    {
      get { return _desId; }
      set { _desId = value; }
    }

    private float _time = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float time
    {
      get { return _time; }
      set { _time = value; }
    }

    private int _intervalTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"intervalTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int intervalTime
    {
      get { return _intervalTime; }
      set { _intervalTime = value; }
    }

    private float _effectValue = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"effectValue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float effectValue
    {
      get { return _effectValue; }
      set { _effectValue = value; }
    }

    private int _mechanicsId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mechanicsId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mechanicsId
    {
      get { return _mechanicsId; }
      set { _mechanicsId = value; }
    }

    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightCmdSynResp")]
  public partial class FightCmdSynResp : global::ProtoBuf.IExtensible
  {
    public FightCmdSynResp() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }

    private long _releaseTime = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"releaseTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long releaseTime
    {
      get { return _releaseTime; }
      set { _releaseTime = value; }
    }
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.DoubleIntProto> _effectJudgeTypes = new global::System.Collections.Generic.List<Logic.Protocol.Model.DoubleIntProto>();
    [global::ProtoBuf.ProtoMember(4, Name=@"effectJudgeTypes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.DoubleIntProto> effectJudgeTypes
    {
      get { return _effectJudgeTypes; }
    }
  
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.Mechanics> _mechanicsList = new global::System.Collections.Generic.List<Logic.Protocol.Model.Mechanics>();
    [global::ProtoBuf.ProtoMember(5, Name=@"mechanicsList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.Mechanics> mechanicsList
    {
      get { return _mechanicsList; }
    }
  
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.Buff> _newBuffList = new global::System.Collections.Generic.List<Logic.Protocol.Model.Buff>();
    [global::ProtoBuf.ProtoMember(6, Name=@"newBuffList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.Buff> newBuffList
    {
      get { return _newBuffList; }
    }
  
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.Buff> _delBuffList = new global::System.Collections.Generic.List<Logic.Protocol.Model.Buff>();
    [global::ProtoBuf.ProtoMember(7, Name=@"delBuffList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.Buff> delBuffList
    {
      get { return _delBuffList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _diedHeroList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"diedHeroList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> diedHeroList
    {
      get { return _diedHeroList; }
    }
  
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.DoubleIntProto> _rebornList = new global::System.Collections.Generic.List<Logic.Protocol.Model.DoubleIntProto>();
    [global::ProtoBuf.ProtoMember(9, Name=@"rebornList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.DoubleIntProto> rebornList
    {
      get { return _rebornList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightStartReq")]
  public partial class FightStartReq : global::ProtoBuf.IExtensible
  {
    public FightStartReq() {}
    
    private int _fightId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillReq")]
  public partial class SkillReq : global::ProtoBuf.IExtensible
  {
    public SkillReq() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private int _fightId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightOver")]
  public partial class FightOver : global::ProtoBuf.IExtensible
  {
    public FightOver() {}
    
    private int _fightId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }
    private int _winRoleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"winRoleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int winRoleId
    {
      get { return _winRoleId; }
      set { _winRoleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightOverResp")]
  public partial class FightOverResp : global::ProtoBuf.IExtensible
  {
    public FightOverResp() {}
    
    private bool _isWin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isWin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isWin
    {
      get { return _isWin; }
      set { _isWin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}