//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: guild.proto
namespace Logic.Protocol.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildLogProto")]
  public partial class GuildLogProto : global::ProtoBuf.IExtensible
  {
    public GuildLogProto() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private long _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _params = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"params", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> @params
    {
      get { return _params; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildRoleProto")]
  public partial class GuildRoleProto : global::ProtoBuf.IExtensible
  {
    public GuildRoleProto() {}
    
    private int _remainPresentTimes;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"remainPresentTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int remainPresentTimes
    {
      get { return _remainPresentTimes; }
      set { _remainPresentTimes = value; }
    }

    private bool _isSign = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isSign", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isSign
    {
      get { return _isSign; }
      set { _isSign = value; }
    }
    private int _devote;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"devote", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int devote
    {
      get { return _devote; }
      set { _devote = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildInfoProto")]
  public partial class GuildInfoProto : global::ProtoBuf.IExtensible
  {
    public GuildInfoProto() {}
    

    private int _no = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int no
    {
      get { return _no; }
      set { _no = value; }
    }

    private int _headNo = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"headNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headNo
    {
      get { return _headNo; }
      set { _headNo = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _lv = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }

    private string _presidentName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"presidentName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string presidentName
    {
      get { return _presidentName; }
      set { _presidentName = value; }
    }

    private int _currNum = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"currNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int currNum
    {
      get { return _currNum; }
      set { _currNum = value; }
    }

    private int _maxNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"maxNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxNum
    {
      get { return _maxNum; }
      set { _maxNum = value; }
    }

    private string _notice = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string notice
    {
      get { return _notice; }
      set { _notice = value; }
    }

    private int _exp = (int)-1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.GuildLogProto> _logList = new global::System.Collections.Generic.List<Logic.Protocol.Model.GuildLogProto>();
    [global::ProtoBuf.ProtoMember(10, Name=@"logList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.GuildLogProto> logList
    {
      get { return _logList; }
    }
  

    private Logic.Protocol.Model.GuildRoleProto _roleGuild = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"roleGuild", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Logic.Protocol.Model.GuildRoleProto roleGuild
    {
      get { return _roleGuild; }
      set { _roleGuild = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildResp")]
  public partial class GuildResp : global::ProtoBuf.IExtensible
  {
    public GuildResp() {}
    
    private Logic.Protocol.Model.GuildInfoProto _guildInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guildInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Logic.Protocol.Model.GuildInfoProto guildInfo
    {
      get { return _guildInfo; }
      set { _guildInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildListResp")]
  public partial class GuildListResp : global::ProtoBuf.IExtensible
  {
    public GuildListResp() {}
    
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.GuildInfoProto> _guildList = new global::System.Collections.Generic.List<Logic.Protocol.Model.GuildInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"guildList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.GuildInfoProto> guildList
    {
      get { return _guildList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _alreadyApplys = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"alreadyApplys", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> alreadyApplys
    {
      get { return _alreadyApplys; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildMemberProto")]
  public partial class GuildMemberProto : global::ProtoBuf.IExtensible
  {
    public GuildMemberProto() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _roleName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private int _lv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _headNo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"headNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headNo
    {
      get { return _headNo; }
      set { _headNo = value; }
    }

    private long _lastLoginTime = (long)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lastLoginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long lastLoginTime
    {
      get { return _lastLoginTime; }
      set { _lastLoginTime = value; }
    }

    private int _job = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int job
    {
      get { return _job; }
      set { _job = value; }
    }

    private int _devot = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"devot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int devot
    {
      get { return _devot; }
      set { _devot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildMemberListResp")]
  public partial class GuildMemberListResp : global::ProtoBuf.IExtensible
  {
    public GuildMemberListResp() {}
    
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.GuildMemberProto> _memberList = new global::System.Collections.Generic.List<Logic.Protocol.Model.GuildMemberProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"memberList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.GuildMemberProto> memberList
    {
      get { return _memberList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildCreateReq")]
  public partial class GuildCreateReq : global::ProtoBuf.IExtensible
  {
    public GuildCreateReq() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _headNo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"headNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headNo
    {
      get { return _headNo; }
      set { _headNo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildShopGood")]
  public partial class GuildShopGood : global::ProtoBuf.IExtensible
  {
    public GuildShopGood() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _no;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int no
    {
      get { return _no; }
      set { _no = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildShopInfoResp")]
  public partial class GuildShopInfoResp : global::ProtoBuf.IExtensible
  {
    public GuildShopInfoResp() {}
    
    private readonly global::System.Collections.Generic.List<int> _hasBuy = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"hasBuy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> hasBuy
    {
      get { return _hasBuy; }
    }
  
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.GuildShopGood> _guildShopInfo = new global::System.Collections.Generic.List<Logic.Protocol.Model.GuildShopGood>();
    [global::ProtoBuf.ProtoMember(2, Name=@"guildShopInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.GuildShopGood> guildShopInfo
    {
      get { return _guildShopInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildAutoPassReq")]
  public partial class GuildAutoPassReq : global::ProtoBuf.IExtensible
  {
    public GuildAutoPassReq() {}
    
    private int _autoAgree;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"autoAgree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int autoAgree
    {
      get { return _autoAgree; }
      set { _autoAgree = value; }
    }

    private int _autoAgreeLv = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"autoAgreeLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int autoAgreeLv
    {
      get { return _autoAgreeLv; }
      set { _autoAgreeLv = value; }
    }

    private int _autoAgreeCombat = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"autoAgreeCombat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int autoAgreeCombat
    {
      get { return _autoAgreeCombat; }
      set { _autoAgreeCombat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}