//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace Logic.Protocol.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }

    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }

    private string _devicesId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"devicesId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string devicesId
    {
      get { return _devicesId; }
      set { _devicesId = value; }
    }

    private int _devicesType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"devicesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int devicesType
    {
      get { return _devicesType; }
      set { _devicesType = value; }
    }

    private string _appPackage = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"appPackage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string appPackage
    {
      get { return _appPackage; }
      set { _appPackage = value; }
    }

    private string _token = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }

    private int _partnerId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"partnerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int partnerId
    {
      get { return _partnerId; }
      set { _partnerId = value; }
    }

    private string _u8token = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"u8token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string u8token
    {
      get { return _u8token; }
      set { _u8token = value; }
    }

    private string _u8userID = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"u8userID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string u8userID
    {
      get { return _u8userID; }
      set { _u8userID = value; }
    }

    private bool _isU8 = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"isU8", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isU8
    {
      get { return _isU8; }
      set { _isU8 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResp")]
  public partial class LoginResp : global::ProtoBuf.IExtensible
  {
    public LoginResp() {}
    
    private long _serverTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serverTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long serverTime
    {
      get { return _serverTime; }
      set { _serverTime = value; }
    }
    private int _roleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _roleName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }

    private string _devicesId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"devicesId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string devicesId
    {
      get { return _devicesId; }
      set { _devicesId = value; }
    }

    private int _devicesType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"devicesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int devicesType
    {
      get { return _devicesType; }
      set { _devicesType = value; }
    }

    private string _appPackage = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"appPackage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string appPackage
    {
      get { return _appPackage; }
      set { _appPackage = value; }
    }
    private int _lv;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }

    private int _headNo = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"headNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headNo
    {
      get { return _headNo; }
      set { _headNo = value; }
    }

    private int _guideNo = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"guideNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guideNo
    {
      get { return _guideNo; }
      set { _guideNo = value; }
    }

    private int _guideNo2 = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"guideNo2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guideNo2
    {
      get { return _guideNo2; }
      set { _guideNo2 = value; }
    }

    private int _serverId = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"serverId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int serverId
    {
      get { return _serverId; }
      set { _serverId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoleReq")]
  public partial class CreateRoleReq : global::ProtoBuf.IExtensible
  {
    public CreateRoleReq() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }

    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }

    private string _devicesId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"devicesId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string devicesId
    {
      get { return _devicesId; }
      set { _devicesId = value; }
    }

    private int _devicesType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"devicesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int devicesType
    {
      get { return _devicesType; }
      set { _devicesType = value; }
    }

    private string _appPackage = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"appPackage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string appPackage
    {
      get { return _appPackage; }
      set { _appPackage = value; }
    }
    private string _roleName;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _hairCutId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"hairCutId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hairCutId
    {
      get { return _hairCutId; }
      set { _hairCutId = value; }
    }
    private int _hairColorId;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"hairColorId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hairColorId
    {
      get { return _hairColorId; }
      set { _hairColorId = value; }
    }
    private int _faceId;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"faceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int faceId
    {
      get { return _faceId; }
      set { _faceId = value; }
    }
    private int _skinId;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"skinId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skinId
    {
      get { return _skinId; }
      set { _skinId = value; }
    }

    private int _partnerId = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"partnerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int partnerId
    {
      get { return _partnerId; }
      set { _partnerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoleResp")]
  public partial class CreateRoleResp : global::ProtoBuf.IExtensible
  {
    public CreateRoleResp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRoleResp")]
  public partial class PlayerRoleResp : global::ProtoBuf.IExtensible
  {
    public PlayerRoleResp() {}
    

    private bool _isNeedCDKey = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isNeedCDKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isNeedCDKey
    {
      get { return _isNeedCDKey; }
      set { _isNeedCDKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientReadyReq")]
  public partial class ClientReadyReq : global::ProtoBuf.IExtensible
  {
    public ClientReadyReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaseResourceInfo")]
  public partial class BaseResourceInfo : global::ProtoBuf.IExtensible
  {
    public BaseResourceInfo() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifyCDKEYReq")]
  public partial class VerifyCDKEYReq : global::ProtoBuf.IExtensible
  {
    public VerifyCDKEYReq() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }

    private int _partnerId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"partnerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int partnerId
    {
      get { return _partnerId; }
      set { _partnerId = value; }
    }
    private string _cdkey;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cdkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string cdkey
    {
      get { return _cdkey; }
      set { _cdkey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaseResourceSyn")]
  public partial class BaseResourceSyn : global::ProtoBuf.IExtensible
  {
    public BaseResourceSyn() {}
    
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.BaseResourceInfo> _resourceInfos = new global::System.Collections.Generic.List<Logic.Protocol.Model.BaseResourceInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"resourceInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.BaseResourceInfo> resourceInfos
    {
      get { return _resourceInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleLvAndExpResp")]
  public partial class RoleLvAndExpResp : global::ProtoBuf.IExtensible
  {
    public RoleLvAndExpResp() {}
    
    private int _lv;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RedPointPromptResp")]
  public partial class RedPointPromptResp : global::ProtoBuf.IExtensible
  {
    public RedPointPromptResp() {}
    
    private int _funcId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"funcId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int funcId
    {
      get { return _funcId; }
      set { _funcId = value; }
    }

    private int _subFuncId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"subFuncId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int subFuncId
    {
      get { return _subFuncId; }
      set { _subFuncId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleHeadReq")]
  public partial class RoleHeadReq : global::ProtoBuf.IExtensible
  {
    public RoleHeadReq() {}
    
    private int _headNo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"headNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headNo
    {
      get { return _headNo; }
      set { _headNo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleHeadResp")]
  public partial class RoleHeadResp : global::ProtoBuf.IExtensible
  {
    public RoleHeadResp() {}
    
    private int _headNo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"headNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headNo
    {
      get { return _headNo; }
      set { _headNo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleNameReq")]
  public partial class RoleNameReq : global::ProtoBuf.IExtensible
  {
    public RoleNameReq() {}
    
    private string _roleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleNameResp")]
  public partial class RoleNameResp : global::ProtoBuf.IExtensible
  {
    public RoleNameResp() {}
    
    private string _roleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuideReq")]
  public partial class GuideReq : global::ProtoBuf.IExtensible
  {
    public GuideReq() {}
    
    private int _no;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int no
    {
      get { return _no; }
      set { _no = value; }
    }

    private int _guideNo2 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guideNo2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guideNo2
    {
      get { return _guideNo2; }
      set { _guideNo2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PayOrderNoReq")]
  public partial class PayOrderNoReq : global::ProtoBuf.IExtensible
  {
    public PayOrderNoReq() {}
    

    private string _productName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"productName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string productName
    {
      get { return _productName; }
      set { _productName = value; }
    }

    private string _productDes = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"productDes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string productDes
    {
      get { return _productDes; }
      set { _productDes = value; }
    }

    private string _productTitle = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"productTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string productTitle
    {
      get { return _productTitle; }
      set { _productTitle = value; }
    }

    private int _productNo = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"productNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int productNo
    {
      get { return _productNo; }
      set { _productNo = value; }
    }

    private int _money = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }

    private string _extension = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"extension", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extension
    {
      get { return _extension; }
      set { _extension = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PayOrderNoResp")]
  public partial class PayOrderNoResp : global::ProtoBuf.IExtensible
  {
    public PayOrderNoResp() {}
    

    private int _stateCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stateCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stateCode
    {
      get { return _stateCode; }
      set { _stateCode = value; }
    }

    private string _orderID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"orderID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string orderID
    {
      get { return _orderID; }
      set { _orderID = value; }
    }

    private string _extension = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"extension", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extension
    {
      get { return _extension; }
      set { _extension = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCreateTimeReq")]
  public partial class GetCreateTimeReq : global::ProtoBuf.IExtensible
  {
    public GetCreateTimeReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCreateTimeResp")]
  public partial class GetCreateTimeResp : global::ProtoBuf.IExtensible
  {
    public GetCreateTimeResp() {}
    
    private string _creatTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"creatTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string creatTime
    {
      get { return _creatTime; }
      set { _creatTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReconnectReq")]
  public partial class ReconnectReq : global::ProtoBuf.IExtensible
  {
    public ReconnectReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReconnectResp")]
  public partial class ReconnectResp : global::ProtoBuf.IExtensible
  {
    public ReconnectResp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientActiveReq")]
  public partial class ClientActiveReq : global::ProtoBuf.IExtensible
  {
    public ClientActiveReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}