//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pack.proto
namespace Logic.Protocol.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackReq")]
  public partial class PackReq : global::ProtoBuf.IExtensible
  {
    public PackReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackResp")]
  public partial class PackResp : global::ProtoBuf.IExtensible
  {
    public PackResp() {}
    
    private int _heroCellNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroCellNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroCellNum
    {
      get { return _heroCellNum; }
      set { _heroCellNum = value; }
    }

    private int _heroCellBuyNum = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroCellBuyNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int heroCellBuyNum
    {
      get { return _heroCellBuyNum; }
      set { _heroCellBuyNum = value; }
    }
    private int _equipCellNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"equipCellNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equipCellNum
    {
      get { return _equipCellNum; }
      set { _equipCellNum = value; }
    }

    private int _equipCellBuyNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"equipCellBuyNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipCellBuyNum
    {
      get { return _equipCellBuyNum; }
      set { _equipCellBuyNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyPackCellReq")]
  public partial class BuyPackCellReq : global::ProtoBuf.IExtensible
  {
    public BuyPackCellReq() {}
    
    private int _packType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"packType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packType
    {
      get { return _packType; }
      set { _packType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyPackCellResp")]
  public partial class BuyPackCellResp : global::ProtoBuf.IExtensible
  {
    public BuyPackCellResp() {}
    
    private int _packType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"packType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packType
    {
      get { return _packType; }
      set { _packType = value; }
    }
    private int _cellNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cellNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cellNum
    {
      get { return _cellNum; }
      set { _cellNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IllustrationReq")]
  public partial class IllustrationReq : global::ProtoBuf.IExtensible
  {
    public IllustrationReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IllustrationProto")]
  public partial class IllustrationProto : global::ProtoBuf.IExtensible
  {
    public IllustrationProto() {}
    
    private int _heroNo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroNo
    {
      get { return _heroNo; }
      set { _heroNo = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _stars = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"stars", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> stars
    {
      get { return _stars; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IllustrationResp")]
  public partial class IllustrationResp : global::ProtoBuf.IExtensible
  {
    public IllustrationResp() {}
    
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.IllustrationProto> _heros = new global::System.Collections.Generic.List<Logic.Protocol.Model.IllustrationProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"heros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.IllustrationProto> heros
    {
      get { return _heros; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _equips = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> equips
    {
      get { return _equips; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _items = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IllustrationSynResp")]
  public partial class IllustrationSynResp : global::ProtoBuf.IExtensible
  {
    public IllustrationSynResp() {}
    
    private readonly global::System.Collections.Generic.List<Logic.Protocol.Model.IllustrationProto> _newHeros = new global::System.Collections.Generic.List<Logic.Protocol.Model.IllustrationProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"newHeros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Logic.Protocol.Model.IllustrationProto> newHeros
    {
      get { return _newHeros; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _equips = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> equips
    {
      get { return _equips; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _items = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}